import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import ScrollToTopButton from '@/components/scroll-top/ScrollToTopButton';
import { NotificationProvider } from '@/context/NotificationContext';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Open Weather Map Manager',
  description: 'Generated by create next app',
  icons: { icon: '/thermostat-icon.svg' }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang={'en'}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <NotificationProvider>
          {children}
          <ScrollToTopButton />
        </NotificationProvider>
      </body>
    </html>
  );
}
